<template>
    <section>
        <ul>
            <li v-for="color in redFamily" :key="color">
                {{ color }}
            </li>
        </ul>
    </section>
</template>

<script lang="ts">
    import { defineComponent } from "vue";

    export default defineComponent({
        name: "ColorComponent",
        data() {
            return {
                redFamily: [
                    "#FFEBEE",
                    "#FFCDD2",
                    "#EF9A9A",
                    "#E57373",
                    "#EF5350",
                    "#F44336",
                    "#E53935",
                    "#D32F2F",
                    "#C62828",
                    "#B71C1C",
                ],
                pinkFamily: [
                    "#FCE4EC",
                    "#F8BBD0",
                    "#F48FB1",
                    "#F06292",
                    "#EC407A",
                    "#E91E63",
                    "#D81B60",
                    "#C2185B",
                    "#AD1457",
                    "#880E4F",
                ],
                purpleFamily: [
                    "#F3E5F5",
                    "#E1BEE7",
                    "#CE93D8",
                    "#BA68C8",
                    "#AB47BC",
                    "#9C27B0",
                    "#8E24AA",
                    "#7B1FA2",
                    "#6A1B9A",
                    "#4A148C",
                ],
                blueFamily: [
                    "#E3F2FD",
                    "#BBDEFB",
                    "#90CAF9",
                    "#64B5F6",
                    "#42A5F5",
                    "#2196F3",
                    "#1E88E5",
                    "#1976D2",
                    "#1565C0",
                    "#0D47A1",
                ],
                deepPurpleFamily: [
                    "#EDE7F6",
                    "#D1C4E9",
                    "#B39DDB",
                    "#9575CD",
                    "#7E57C2",
                    "#673AB7",
                    "#5E35B1",
                    "#512DA8",
                    "#4527A0",
                    "#311B92",
                ],
                indigoFamily: [
                    "#E8EAF6",
                    "#C5CAE9",
                    "#9FA8DA",
                    "#7986CB",
                    "#5C6BC0",
                    "#3F51B5",
                    "#3949AB",
                    "#303F9F",
                    "#283593",
                    "#1A237E",
                ],
                lightBlueFamily: [
                    "#e1f5fe",
                    "#b3e5fc",
                    "#81d4fa",
                    "#4fc3f7",
                    "#29b6f6",
                    "#03a9f4",
                    "#039be5",
                    "#0288d1",
                    "#0277bd",
                    "#01579b",
                ],
                cyanFamily: [
                    "#e0f7fa",
                    "#b2ebf2",
                    "#80deea",
                    "#4dd0e1",
                    "#26c6da",
                    "#00bcd4",
                    "#00acc1",
                    "#0097a7",
                    "#00838f",
                    "#006064",
                ],
                tealFamily: [
                    "#e0f2f1",
                    "#b2dfdb",
                    "#80cbc4",
                    "#4db6ac",
                    "#26a69a",
                    "#009688",
                    "#00897b",
                    "#00796b",
                    "#00695c",
                    "#004d40",
                ],
                greenFamily: [
                    "#e8f5e9",
                    "#c8e6c9",
                    "#a5d6a7",
                    "#81c784",
                    "#66bb6a",
                    "#4caf50",
                    "#43a047",
                    "#388e3c",
                    "#2e7d32",
                    "#1b5e20",
                ],
                lightGreenFamily: [
                    "#f1f8e9",
                    "#dcedc8",
                    "#c5e1a5",
                    "#aed581",
                    "#9ccc65",
                    "#8bc34a",
                    "#7cb342",
                    "#689f38",
                    "#558b2f",
                    "#33691e",
                ],
                limeFamily: [
                    "#f9fbe7",
                    "#f0f4c3",
                    "#e6ee9c",
                    "#dce775",
                    "#d4e157",
                    "#cddc39",
                    "#c0ca33",
                    "#afb42b",
                    "#9e9d24",
                    "#827717",
                ],
                yellowFamily: [
                    "#fffde7",
                    "#fff9c4",
                    "#fff59d",
                    "#fff176",
                    "#ffee58",
                    "#ffeb3b",
                    "#fdd835",
                    "#fbc02d",
                    "#f9a825",
                    "#f57f17",
                ],
                amberFamily: [
                    "#fff8e1",
                    "#ffecb3",
                    "#ffe082",
                    "#ffd54f",
                    "#ffca28",
                    "#ffc107",
                    "#ffb300",
                    "#ffa000",
                    "#ff8f00",
                    "#ff6f00",
                ],
                orangeFamily: [
                    "#fff3e0",
                    "#ffe0b2",
                    "#ffcc80",
                    "#ffb74d",
                    "#ffa726",
                    "#ff9800",
                    "#fb8c00",
                    "#f57c00",
                    "#ef6c00",
                    "#e65100",
                ],
                deepOrangeFamily: [
                    "#fbe9e7",
                    "#ffccbc",
                    "#ffab91",
                    "#ff8a65",
                    "#ff7043",
                    "#ff5722",
                    "#f4511e",
                    "#e64a19",
                    "#d84315",
                    "#bf360c",
                ],
                brownFamily: [
                    "#efebe9",
                    "#d7ccc8",
                    "#bcaaa4",
                    "#a1887f",
                    "#8d6e63",
                    "#795548",
                    "#6d4c41",
                    "#5d4037",
                    "#4e342e",
                    "#3e2723",
                ],
                greyFamily: [
                    "#fafafa",
                    "#f5f5f5",
                    "#eeeeee",
                    "#e0e0e0",
                    "#bdbdbd",
                    "#9e9e9e",
                    "#757575",
                    "#616161",
                    "#424242",
                    "#212121",
                ],
                blueGreyFamily: [
                    "#eceff1",
                    "#cfd8dc",
                    "#b0bec5",
                    "#90a4ae",
                    "#78909c",
                    "#607d8b",
                    "#546e7a",
                    "#455a64",
                    "#37474f",
                    "#263238",
                ],
            };
        },
    });
</script>
